language: cpp
sudo: required
before_install:
  - sudo apt-get install cmake
compiler:
  - clang++
  script: 
    - cmake
  
os:
  - osx

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost_signals.a
      - libboost_signals.dylib
      
    
