language: cpp
sudo: required
compiler:
  - clang++
  script: 
    - make
  
os:
  - osx

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost_signals.a
      - libboost_signals.dylib
      
    
